### ISSUE TITLE
Remove static "popular content"

### ISSUE THREAD

**Issue by sosaemilio** [sosaemilio/sleepoutside-wdd330#7]
https://github.com/sosaemilio/sleepoutside-wdd330/blob/aa0e8accb4fc63e534b1f71174ccb14ed10ff70c/src/index.html#LL67C1-L67C1

I noticed we forgot to comment or remove the static content section.

**Comment by sosaemilio** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove static "popular content"](https://trello.com/c/gOSJqCZs/11-remove-static-popular-content)

**Comment by reiquel** [comment]
Thank you noticing!

**Comment by sosaemilio** [comment]
We can't close the issue until it is fixed.

**Comment by reiquel** [comment]
Right I understand, I closed by mistake, sorry about that.

**Comment by reiquel** [comment]
I already updated it on my end, there was another thing that needed to be fixed which was the productList.mjs module, that I made a change on, please verify my branch to see if it is fine to accept my pull request.

**Comment by sosaemilio** [comment]
The ticket was successfully solved on the branch #8
